@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
 class Car{
- carBrand:string
- carModel:string
- VIN:string
}

class Client{
- firstName:string
- lastName:string
- phoneNumber:string
- email:string
}
class Workshop{
+isAvaiable():bool
}
note left of Workshop
    Gdy isAvailable() == true,
możemy przyjąć kolejny pojazd.
Tzn. repaired dla każdej z usług w klasie Repair
 musi zwracać true.
end note
abstract PartService {
-name:string
-repaired:bool
-PartHourlyPrice:int
-beginTime:ptime
-endTime:ptime
+endService(endTime:ptime):void
+getServiceCost():int
+getInfo():string
}
note right of PartService
    getServiceCost() zwraca koszt wykonania pojedynczej
uslugi poniewaz naprawa moze dotyczec wielu usług
np. 1h wymiana tarcz hamulcowych oraz
6h wymiana rozrządu bez mnożnika
    getInfo() zwraca wyraz skladajacy sie z
wszystkich atrybutow i jest wirtualny
end note
class PartRegeneration{
+getInfo():string
}
class NewPartReplacement{
-NewPartPrice:int
+getInfo():string
}
note bottom of NewPartReplacement
    getServiceCost() nadpisuje metodę bazową dodając
do kosztów robocizny cenę zakupu nowej części (NewPartPrice)
end note
class Repair{
-id:int
-repairCost:int
+calculateTotal():int
+getServicesAmount():int
+getSingleServiceCost(serwis:PartService):int
}
note right of Repair
    calculateTotal() oblicza repairCost, czyli ile ma zapłacić klient
za wykonaną naprawę. Sumę wszystkich usług.
    getSingleServiceCost() zwraca getServiceCost() pomnożony
przez mnożnik pozyskany z getMultiplier
end note
abstract PoweredBy{
+getMultiplier():double
}
note left of PoweredBy
getMultiplier() jest czysto wirtualny
zwraca okreslony mnoznik
- dla benzyny 1.0
- dla Diesla 1.2
- dla baterii(samochodu elektrycznego) 1.5
end note
abstract Engine{
-engineDisplacement:int
+getMultiplier():double
}
note bottom of Engine
getMultiplier() dla klasy Engine jest zalezny rowniez od jego pojemnosci
- ponizej 1000cm3 wynosi 1.0
- od 1000cm3 do 2000cm3 rosnie liniowo
  od 1.0 do 1.5
- od 2000cm3 do 6000cm3 rowniez rosnie liniowo
  od 1.5 do 3.0
getMultiplier() w przypadku Diesla zwraca odpowiedni mnoznik
dla pojemnosci silnika pomnozony analogicznie przez 1.2
end note
class Accumulator{
+getMultiplier():double
}
class DieselEngine{
+getMultiplier():double

}
class PetrolEngine{
+getMultiplier():double
}
Workshop "1" *-- "0..* " Repair : zarządza
Client "1" -- "0..*" Car : posiada
Repair "0..*" -- "1" Car : dotyczy
Repair "1" *-- "1..*  " PartService : składa się z
PartService <|-- NewPartReplacement
PartService <|-- PartRegeneration
Car"1" *-- "1"PoweredBy
PoweredBy <|-- Engine
PoweredBy <|-- Accumulator
Engine <|-- DieselEngine
Engine <|-- PetrolEngine
@enduml