@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class LogicContainer {
-clientManager: ClientManager
-repairManager: RepairManager
-resourceManager: ResourceManager
+getClientManager(): ClientManager&
+getRepairManager(): RepairManager&
+getResourceManager(): ResourceManager&
}
note right of LogicContainer
  Kontener z zarządcami.
end note

class ClientManager {
-clientRepository: ClientRepository
+registerClient(fName: string, lName: string, pID: string, mail: string, phone: string): ClientPtr
+unregisterClient(id: string): void
+getClient(id: string): ClientPtr
+findClients(predicate: ClientPredicate): vector<ClientPtr>
+findAllClients(): vector<ClientPtr>
}
note bottom of ClientManager
  Zarządza cyklem życia obiektów Client.
  Odpowiada za walidację danych przed dodaniem
  klienta do repozytorium.
end note

class RepairManager {
-repairRepository: RepairRepository
+getRepair(id: int): RepairPtr
+beginRepair(client: ClientPtr, car: CarPtr, res: vector<ResourcePtr>): RepairPtr
+finishRepair(repair: RepairPtr, time: ptime): void
+findRepairs(predicate: RepairPredicate): vector<RepairPtr>
+findAllRepairs(): vector<RepairPtr>
+getClientRepairs(client: ClientPtr): vector<RepairPtr>
}
note bottom of RepairManager
  Koordynuje proces naprawy: łączy klienta, pojazd
  i zasoby. Przy kończeniu naprawy wywołuje
  obliczanie kosztów końcowych.
end note

class ResourceManager {
-resourceRepository: ResourceRepository
+getMechanic(mechanic: ResourcePtr): ResourcePtr
+assignMechanicToRepair(mechanic: ResourcePtr): void
+registerMechanic(fName: string, lName: string, hasEV: bool): ResourcePtr
+unregisterMechanic(mechanic: ResourcePtr): void
+checkAvailability(res: ResourcePtr): bool
+findAvailableMechanics(): vector<ResourcePtr>
+findMechanics(predicate: ResourcePredicate): vector<ResourcePtr>
+findAllMechanics(): vector<ResourcePtr>
}
note top of ResourceManager
  Zarządza zasobami warsztatu. Implementuje
  logikę sprawdzania dostępności poprzez
  tworzenie odpowiednich predykatów.
end note

class ClientRepository {
-clients: vector<ClientPtr>
+get(index: int): ClientPtr
+add(client: ClientPtr): void
+remove(client: ClientPtr): void
+size(): int
+report(): string
+findAll(): vector<ClientPtr>
+findBy(predicate: ClientPredicate): vector<ClientPtr>
+findByPersonalId(id: string): ClientPtr
}
note bottom of ClientRepository: Repozytorium przechowujące Klientów. Wyszukiwanie m.in. po PESEL.

class RepairRepository {
-repairs: vector<RepairPtr>
+get(index: int): RepairPtr
+add(repair: RepairPtr): void
+remove(repair: RepairPtr): void
+size(): int
+report(): string
+findAll(): vector<RepairPtr>
+findBy(predicate: RepairPredicate): vector<RepairPtr>
+findById(id: int): RepairPtr
}
note bottom of RepairRepository: Zarządza zleceniami. Wyszukiwanie po ID.

class ResourceRepository {
-resources: vector<ResourcePtr>
+get(index: int): ResourcePtr
+add(resource: ResourcePtr): void
+remove(resource: ResourcePtr): void
+size(): int
+report(): string
+findAll(): vector<ResourcePtr>
+findBy(predicate: ResourcePredicate): vector<ResourcePtr>
}
note bottom of ResourceRepository: Repozytorium zasobów (Mechaników).

class ClientPredicate <<function>>
class RepairPredicate <<function>>
class ResourcePredicate <<function>>


' <--- RELACJE --->

LogicContainer *-- ClientManager
LogicContainer *-- RepairManager
LogicContainer *-- ResourceManager

ClientManager *-- ClientRepository
RepairManager *-- RepairRepository
ResourceManager *-- ResourceRepository

ClientManager ..> ClientPredicate
RepairManager ..> RepairPredicate
ResourceManager ..> ResourcePredicate
ClientRepository ..> ClientPredicate
RepairRepository ..> RepairPredicate
ResourceRepository ..> ResourcePredicate

ClientRepository --> Client
RepairRepository --> Repair
ResourceRepository --> Mechanic

RepairManager ..> Client : używa
RepairManager ..> Repair : tworzy i modyfikuje
RepairManager ..> Mechanic : przypisuje do naprawy
ClientManager ..> Client : rejestruje/tworzy
ResourceManager ..> Mechanic : sprawdza dostępność

@enduml