@startuml
skinparam classAttributeIconSize 0

class ClientRepository {
    - clients : std::vector<ClientPtr>
}
note bottom of ClientRepository
  Repozytorium przechowuje klientów.
end note

class CarRepository {
    - cars : std::vector<CarPtr>
}
note bottom of CarRepository
  Repozytorium przechowuje samochody.
end note

class MechanicRepository {
    - mechanics : std::vector<MechanicPtr>
}
note bottom of MechanicRepository
  Repozytorium przechowuje mechaników.
end note

class RepairRepository {
    - repairs : std::vector<RepairPtr>
}
note bottom of RepairRepository
  Repozytorium przechowuje naprawy.
end note

class ResourceRepository {
    - resources : std::vector<ResourcePtr>
}
note bottom of ResourceRepository
  Przechowuje zasoby warsztatu.
end note

class StorageContainer {
    - clientRepository : ClientRepository
    - carRepository : CarRepository
    - mechanicRepository : MechanicRepository
    - repairRepository : RepairRepository
    - resourceRepository : ResourceRepository
}
note left of StorageContainer
  Klasa bazy danych:
  - tworzy repozytoria
  - wypełnia je danymi (z pliku lub testowymi)
end note

class ClientPredicate <<typedef std::function>>
class CarPredicate <<typedef std::function>>
class MechanicPredicate <<typedef std::function>>
class RepairPredicate <<typedef std::function>>
class ResourcePredicate <<typedef std::function>>

' Agregacja repozytoriów w kontenerze danych
StorageContainer "1" *-- "1" ClientRepository
StorageContainer "1" *-- "1" CarRepository
StorageContainer "1" *-- "1" MechanicRepository
StorageContainer "1" *-- "1" RepairRepository
StorageContainer "1" *-- "1" ResourceRepository

ClientRepository "1" --> "0..*" Client
RepairRepository "1" --> "0..*" Repair
ResourceRepository "1" --> "0..*" Resource
CarRepository "1" --> "0..*" Car
MechanicRepository "1" --> "0..*" Mechanic

' Użycie predykatów funkcyjnych
ClientRepository ..> ClientPredicate
CarRepository ..> CarPredicate
MechanicRepository ..> MechanicPredicate
RepairRepository ..> RepairPredicate
ResourceRepository ..> ResourcePredicate

note bottom of StorageContainer : Odpowiada za bezpośredni zapis i odczyt\nwszystkich repozytoriów przy użyciu boost::archive
@enduml